
# 开发环境配置

# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*.xml

# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    # 禁用默认分组，避免与自定义分组重复
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  # 禁用默认的全局API文档生成，只使用分组
  default-flat-param-object: false
  # 只扫描指定包，避免生成默认分组
  packages-to-scan: com.admin.module

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-version: true
    enable-reload-cache-parameter: true
    enable-after-script: true
    enable-filter-multipart-apis: true
    enable-filter-multipart-api-method-type: POST
    enable-request-cache: true
    enable-home-custom: true
    home-custom-path: classpath:knife4j/home.md
  # 自定义文档配置 - 移除默认分组配置
  # documents:
  #   - group: default
  #     name: 接口文档说明
  #     locations: classpath:knife4j/home.md
  openapi:
    title: Admin管理系统API文档
    description: Admin管理系统后端接口文档
    version: 1.0.0
    contact:
      name: Admin Team
      email: admin@example.com

# JWT认证配置
admin:
  jwt:
    secret: adminSecretKeyForJWTTokenGenerationMustBeLongEnoughForHS512
    expiration: 1800000  # 访问令牌过期时间：30分钟（毫秒）
    refresh-expiration: 2592000000  # 刷新令牌过期时间：30天（毫秒）
  
  # MinIO对象存储配置
  minio:
    enabled: true
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    default-bucket: admin-dev
    connect-timeout: 10000
    write-timeout: 60000
    read-timeout: 10000
    upload:
      max-file-size: 100  # 最大文件大小（MB）
      allowed-types:
        - jpg
        - jpeg
        - png
        - gif
        - bmp
        - webp
        - pdf
        - doc
        - docx
        - xls
        - xlsx
        - ppt
        - pptx
        - txt
        - mp4
        - avi
        - mkv
        - mov
        - wmv
        - mp3
        - wav
        - flac
        - aac
        - zip
        - rar
        - 7z
        - tar
        - gz
      file-name-strategy: UUID  # 文件名生成策略：UUID、DATE、ORIGINAL
      keep-original-name: false
      path-prefix: "uploads/"
    download:
      presigned-url-expiry: 3600  # 预签名URL过期时间（秒）
      enable-range-download: true  # 是否启用断点续传
      cache-control: "max-age=3600"
  
  # 日志切面配置
  log:
    aspect:
      enabled: true
      async-enabled: true
      max-param-length: 2000
      max-result-length: 4000
      max-error-length: 1000
      exclude-patterns:
        - "*/health/**"
        - "*/metrics/**"
        - "*/actuator/**"
      async:
        core-pool-size: 2
        max-pool-size: 8
        queue-capacity: 500
        thread-name-prefix: "LogAspect-"
        keep-alive-seconds: 60

# 日志配置
logging:
  level:
    com.admin: debug
    org.springframework.web: debug
    com.baomidou.mybatisplus: debug